### ISSUE TITLE
Choppy animation on the newest version of Firefox

### ISSUE THREAD

**Issue by bedax** [Stanko/animated-scroll-to#22] opened 2018-06-13 14:13 UTC
Hello, this library has been working very well for me, but I have tested it on the latest version of Firefox (61.0b10), and it is now not animating smoothly.

I am on Debian 9.4 (64-bit). On Firefox 52.8.1 it is fine, as it is on Chromium 66.0.3359.117.

If it helps, here are some plugins that animate smoothly on the newest Firefox:

- https://noeldelgado.github.io/pisces/
- https://cferdinandi.github.io/smooth-scroll/
- https://hsnaydd.github.io/moveTo/demo/
- https://tsuyoshiwada.github.io/sweet-scroll/

And here are some that are affected by the same problem (in case cross-comparing them helps you find the bug):

- https://bupy7.github.io/js-animate-scroll/
- https://github.com/serieseight/tinyscroll

Either way, thank you for this plugin, it has a nice API and I would prefer to continue using it.

**Comment by ambazaar** [comment] 2018-06-13 14:54
Hi @Stanko. There's nothing in the console, and I tried various different options and nothing changed it. Seems like a tricky one to track down.

**Comment by bedax** [comment] 2018-06-13 14:54
Hi @Stanko. There's nothing in the console, and I tried various different options and nothing changed it. Seems like a tricky one to track down.

**Comment by Stanko** [comment] 2018-09-13 12:41
Closing, as I can't reproduce it.

**Closed** 2018-09-13 12:42 UTC
